server:
  port: 8083

grpc:
  server:
    port: 9091


## 用于Consul健康检查
endpoints:
  actuator:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false

thrift:
  port: 8895
  min-thread-pool: 100
  max-thread-pool: 1000

spring:
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        prefer-ip-address: true
      port: 8500